base:
  project_name: ALOI
  seed: 91
  lr: 0.005
  weight_decay: 0.00005
  batch_size: 2160
  n_epochs: 200
  num_workers: 8
  gpu_id: 1
  num_classes: 100
  num_views: 4
  annealing_step: 1000
  w : 2
  alpha: 0.2
  beta: 0.0001
  gamma: 0.2
dataset:
  datasetName: ALOI
  dataPath: datasets\ALOI_100.mat
  add_postprocessing: false

