base:
  project_name: PIE
  ckpt_root: ./ckpt
  seed: 13
  lr: 0.005
  weight_decay: 0.00005
  batch_size: 680
  n_epochs: 300
  num_workers: 8
  gpu_id: 1
  num_classes: 68
  num_views: 3
  annealing_step: 50
  loss : edl_HENN
  w : 2
dataset:
  datasetName: PIE
  dataPath: datasets\PIE_face_10.mat
  train_mode: regression

