base:
  project_name: PIE
  seed: 13
  lr: 0.005
  weight_decay: 0.00005
  batch_size: 680
  n_epochs: 300
  num_workers: 8
  gpu_id: 1
  num_classes: 68
  num_views: 3
  annealing_step: 50
  w : 2
  alpha: 1
  beta: 0.0005
  gamma: 1
dataset:
  datasetName: PIE
  dataPath: datasets\PIE_face_10.mat

